### PR TITLE
chore: update Cargo.lock for the new version

### PR DESCRIPTION
**Pull request by orhun**
just a bump :)

### CODE REVIEW

**Comment by orhun** [comment]
I'm not familiar with Nix but it would be a good idea to build with `--locked` flag somewhere in the CI to catch this next time

**Comment by ifd3f** [comment]
Well shit, dumb on me for not catching that. I'll see if I can move the tag forward.

**Comment by ifd3f** [comment]
@orhun the v0.4.8 tag should have been updated to the correct lockfile now. see if it works?

**Comment by ifd3f** [comment]
yes, i can avoid that next time :)

**Pull request merged**
