### PR TITLE
Add run0 support

### LINKED ISSUE #116: run0 support
support escalating through [systemd's run0](https://www.freedesktop.org/software/systemd/man/devel/run0.html)

### PR DESCRIPTION
**Pull request by jschpp**
should be enough to fix #116

### CODE REVIEW

**Comment by jschpp** [comment]
Though I have no idea how to add run0 to [default.nix](https://github.com/ifd3f/caligula/blob/main/checks/autoescalate/default.nix) :sweat_smile:

**Comment by ifd3f** [comment]
I'll look at this in the morning.

**Comment by ifd3f** [comment]
I've added a NixOS test for run0, but in order to enable run0, we need to update NixOS, and that's been blocked on an issue. I've created #151 to track the version update. I'll try to push out a PR that fixes that Soon(tm)

**Comment by jschpp** [comment]
@ifd3f I've tried the polkit rule in the blog article you mentioned. At least on my Desktop it seems to work.
The only thing I did was adding the `/etc/polkit-1/rules.d/10-systemd-nopasswd.rules` file.
I didn't need to add the pam option.

```
[ 11:12:01 ] ❯ id
uid=1000(schoepp) gid=1000(schoepp) Gruppen=1000(schoepp),998(wheel)

~ 
[ 11:12:07 ] ❯ run0 cat /etc/polkit-1/rules.d/10-systemd-nopasswd.rules
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.systemd1.manage-units") {
        if (subject.isInGroup("wheel")) {
            return polkit.Result.YES;
        }
    }
});

~ 
[ 11:12:17 ] ❯ run0 ls /etc/polkit-1/rules.d/
10-systemd-nopasswd.rules

~ 
[ 11:12:22 ] ❯ 
```

**Comment by ifd3f** [comment]
Yea I give up on making the run0 check work. Let's merge this as-is

**Comment by jschpp** [comment]
I'm sorry I couldn't help more. But thank you for merging this. This was pretty much the last thing still holding me back from removing sudo.

**Pull request merged**
